name: app_admin
description: "Created by HoangQuan"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.3.0
  provider: ^6.1.2
  logger: ^2.5.0
  shared_preferences: ^2.4.0
  loading_animation_widget: ^1.3.0
  toastification: ^2.3.0
  flutter_dropdown: ^1.0.1+hotfix.1
  flutter_riverpod: ^2.6.1
  go_router: ^14.7.2
  intl: ^0.20.2
  photo_view: ^0.15.0
  loadmore: ^2.1.0
  bcrypt: ^1.1.3
  url_launcher: ^6.3.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo_border.png"
  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
